OPENAI_API_KEY = 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  # replace with your actual key
